/// Invalid host-side subagent policy.
#[derive(Debug, thiserror::Error)]
pub enum SubagentConfigError {
    /// Two model registrations used the same provider/model/effort combination.
    #[error("subagent model `{provider}/{model}` effort `{effort}` was registered more than once")]
    DuplicateModel {
        /// Provider name.
        provider: String,
        /// Provider-specific model name.
        model: String,
        /// Duplicate effort.
        effort: String,
    },
    /// A registered effort was empty or padded.
    #[error("subagent effort `{effort}` must be nonempty and unpadded")]
    InvalidEffort {
        /// Invalid effort value.
        effort: String,
    },
    /// Two namespaces used the same manifest path.
    #[error("subagent namespace `{path}` was registered more than once")]
    DuplicateNamespace {
        /// Duplicate path.
        path: String,
    },
    /// A host namespace collided with the namespace generated by this crate.
    #[error("subagent namespace `{path}` is reserved by lam-agents")]
    ReservedNamespace {
        /// Reserved path.
        path: String,
    },
}

/// Failure to construct the executor pool.
#[derive(Debug, thiserror::Error)]
pub enum AgentSystemBuildError {
    /// A zero-sized executor pool cannot run actors.
    #[error("agent worker thread count must be greater than zero")]
    ZeroWorkers,
    /// A zero-capacity system cannot host its root actor.
    #[error("maximum resident actor count must be greater than zero")]
    ZeroCapacity,
    /// An executor thread could not be created.
    #[error("failed to start agent worker thread: {0}")]
    ThreadSpawn(#[source] std::io::Error),
    /// A worker could not create its local async runtime.
    #[error("failed to initialize agent worker: {message}")]
    WorkerInitialization {
        /// Runtime diagnostic.
        message: String,
    },
}

/// Failure to host or operate a resident actor.
#[derive(Debug, thiserror::Error)]
pub enum AgentSystemError {
    /// The system has begun shutting down.
    #[error("the agent system is shutting down")]
    ShuttingDown,
    /// The configured actor residency bound was reached.
    #[error("the agent system reached its limit of {max_agents} resident actors")]
    Capacity {
        /// Configured bound.
        max_agents: usize,
    },
    /// A worker stopped accepting actor launches.
    #[error("the selected agent worker is unavailable")]
    WorkerUnavailable,
    /// The actor could not initialize.
    #[error(transparent)]
    ActorBuild(#[from] lam::ActorBuildError),
    /// A hosted actor identity was not a canonical absolute address.
    #[error("invalid actor address `{address}`: {message}")]
    InvalidAddress {
        /// Rejected address text.
        address: String,
        /// Canonicalization diagnostic.
        message: String,
    },
    /// Another resident, launch, or durable actor already owns this address.
    #[error("actor address `{address}` is already in use")]
    AddressInUse {
        /// Conflicting canonical address.
        address: crate::ActorAddress,
    },
    /// An overlapping agent-tree interruption is already in progress.
    #[error("agent tree rooted at `{root}` is being interrupted")]
    InterruptionInProgress {
        /// Root of the interruption boundary.
        root: crate::ActorAddress,
    },
    /// A hosted actor has already stopped and cannot receive operations.
    #[error("actor `{address}` is not running")]
    ActorUnavailable {
        /// Stopped or unknown actor address.
        address: crate::ActorAddress,
    },
    /// A hosted actor task panicked on its local executor.
    #[error("actor `{address}` task panicked")]
    ActorTaskPanicked {
        /// Panicked actor address.
        address: crate::ActorAddress,
    },
    /// A resident actor operation failed.
    #[error(transparent)]
    Actor(#[from] lam::ActorError),
    /// An executor thread panicked while shutting down.
    #[error("agent worker panicked: {message}")]
    WorkerJoin {
        /// Panic diagnostic.
        message: String,
    },
}
