[package]
name = "lam-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lam-agent"
path = "src/main.rs"
doc = false

[dependencies]
arboard = { version = "=3.6.1", default-features = false, features = ["wayland-data-control"] }
base64.workspace = true
crossterm = "=0.29.0"
lam = { path = "../lam" }
lam-agents = { path = "../lam-agents" }
lam-code = { path = "../lam-code" }
lam-openai = { path = "../lam-openai" }
lam-redb = { path = "../lam-redb" }
nix.workspace = true
ratatui.workspace = true
redb.workspace = true
reqwest.workspace = true
ring = "=0.17.14"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tui-markdown.workspace = true
unicode-segmentation = "1.13.3"
unicode-width.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
